package controller;

public enum Event {
	OPEN_HOME_SECTION, OPEN_ADD_SECTION, OPEN_SEARCH_SECTION, OPEN_DELETE_SECTION, OPEN_LIST_SECTION, OPEN_INFO_SECTION, CLEAR_ADD_SECTION, ADD_CONTACT, SEARCH_CONTACT, DELETE_CONTACT

}
